# Generated by Django 4.2.10 on 2024-03-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=30)),
                ('subject', models.CharField(default='', max_length=90)),
                ('message', models.CharField(default=0, max_length=260)),
            ],
        ),
    ]
